#
# Copyright (C) BABEC. All rights reserved.
# Copyright (C) THL A29 Limited, a Tencent company. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

log:
  config_file: ../config/wx-org1/log.yml          # config file of logger configuration.

blockchain:
  - chainId: chain1
    genesis: ../config/wx-org1/chainconfig/bc1.yml
#  - chainId: chain2
#    genesis: ../config/wx-org1/chainconfig/bc2.yml
#  - chainId: chain3
#    genesis: ../config/wx-org1/chainconfig/bc3.yml
#  - chainId: chain4
#    genesis: ../config/wx-org1/chainconfig/bc4.yml

node:
  # 节点类型：full、spv
  type:              full
  org_id:            wx-org1.chainmaker.org
  priv_key_file:     ../config/wx-org1/certs/node/consensus1/consensus1.sign.key
  cert_file:         ../config/wx-org1/certs/node/consensus1/consensus1.sign.crt
  signer_cache_size: 1000
  cert_cache_size:   1000

net:
  provider: LibP2P
  listen_addr: /ip4/0.0.0.0/tcp/11301
  tls:
    enabled: true
    priv_key_file: ../config/wx-org1/certs/node/consensus1/consensus1.tls.key
    cert_file:     ../config/wx-org1/certs/node/consensus1/consensus1.tls.crt

txpool:
  max_txpool_size: 5120 # 普通交易池上限
  max_config_txpool_size: 10 # config交易池的上限
  full_notify_again_time: 30 # 交易池溢出后，再次通知的时间间隔(秒)

rpc:
  provider: grpc
  port: 12301
  tls:
    # TLS模式:
    #   disable - 不启用TLS
    #   oneway  - 单向认证
    #   twoway  - 双向认证
    #mode: disable
    #mode: oneway
    mode:           twoway
    priv_key_file:  ../config/wx-org1/certs/node/consensus1/consensus1.tls.key
    cert_file:      ../config/wx-org1/certs/node/consensus1/consensus1.tls.crt

monitor:
  enabled: false
  port: 14321

pprof:
  enabled: false
  port: 24321

storage:
  provider: levelDB
  store_path: ../data/ledgerData1
  write_buffer_size: 4    #LevelDB、RocksDB的write_buffer_size， 单位为MB，默认为4M
  bloom_filter_bits: 10    #LevelDB、RocksDB的布隆过滤器参数，为每个key分配的额外bit空间，默认为10，如果少于或等于0，则不开启布隆过滤。
  disable_historydb: false    #是否禁用历史读写集的存储功能， 默认为false，也就是保存历史读写集。
  disable_contract_eventdb: true #是否禁用合约事件存储功能， 默认为false，如果设置为true,需要配置mysql
  mysql:    #MySQL相关配置，只有provider选择MySQL时才需要配置
    dsn: root:B1ockch@in@tcp(42.192.47.37:3306)/    #mysql的连接信息，包括用户名、密码、ip、port等，示例：root:admin?@tcp(127.0.0.1:3306)
    max_idle_conns: 10    #连接池中维持的最大的空闲连接数，默认为10
    max_open_conns: 10    #最大的可用连接数，默认为10
    conn_max_lifetime: 60    #连接维持的最长时间，单位秒，默认为60


debug:
  # 是否开启CLI功能，过度期间使用
  is_cli_open: true
  is_http_open: false

