
run:
  timeout: 10m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  #  skip-files:
  skip-dirs:
    - p2p #from libp2p
linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - goimports
    - gosimple
    - govet
    #    - ineffassign
    - misspell
    #    - staticcheck
    - unconvert
    - unused
    - varcheck
    - gosec
#    - lll

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 2 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences

issues:
  exclude-rules:
    - path: .*_test.go
      linters:
        - unused
        - deadcode